// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LivenessNoContentCode is the HTTP code returned for type LivenessNoContent
const LivenessNoContentCode int = 204

/*LivenessNoContent No content

swagger:response livenessNoContent
*/
type LivenessNoContent struct {
}

// NewLivenessNoContent creates LivenessNoContent with default headers values
func NewLivenessNoContent() *LivenessNoContent {

	return &LivenessNoContent{}
}

// WriteResponse to the client
func (o *LivenessNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
