// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ReadinessNoContentCode is the HTTP code returned for type ReadinessNoContent
const ReadinessNoContentCode int = 204

/*ReadinessNoContent No content

swagger:response readinessNoContent
*/
type ReadinessNoContent struct {
}

// NewReadinessNoContent creates ReadinessNoContent with default headers values
func NewReadinessNoContent() *ReadinessNoContent {

	return &ReadinessNoContent{}
}

// WriteResponse to the client
func (o *ReadinessNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
