// Code generated by go-swagger; DO NOT EDIT.

package teacher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/iAmPlus/microservice/models/apimodels"
)

// RetrieveForNotificationsOKCode is the HTTP code returned for type RetrieveForNotificationsOK
const RetrieveForNotificationsOKCode int = 200

/*RetrieveForNotificationsOK Retrieve For Notifications

swagger:response retrieveForNotificationsOK
*/
type RetrieveForNotificationsOK struct {

	/*
	  In: Body
	*/
	Payload *apimodels.Recipients `json:"body,omitempty"`
}

// NewRetrieveForNotificationsOK creates RetrieveForNotificationsOK with default headers values
func NewRetrieveForNotificationsOK() *RetrieveForNotificationsOK {

	return &RetrieveForNotificationsOK{}
}

// WithPayload adds the payload to the retrieve for notifications o k response
func (o *RetrieveForNotificationsOK) WithPayload(payload *apimodels.Recipients) *RetrieveForNotificationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve for notifications o k response
func (o *RetrieveForNotificationsOK) SetPayload(payload *apimodels.Recipients) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveForNotificationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveForNotificationsBadRequestCode is the HTTP code returned for type RetrieveForNotificationsBadRequest
const RetrieveForNotificationsBadRequestCode int = 400

/*RetrieveForNotificationsBadRequest Bad request <br>


swagger:response retrieveForNotificationsBadRequest
*/
type RetrieveForNotificationsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewRetrieveForNotificationsBadRequest creates RetrieveForNotificationsBadRequest with default headers values
func NewRetrieveForNotificationsBadRequest() *RetrieveForNotificationsBadRequest {

	return &RetrieveForNotificationsBadRequest{}
}

// WithPayload adds the payload to the retrieve for notifications bad request response
func (o *RetrieveForNotificationsBadRequest) WithPayload(payload *apimodels.ErrorResponse) *RetrieveForNotificationsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve for notifications bad request response
func (o *RetrieveForNotificationsBadRequest) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveForNotificationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveForNotificationsUnauthorizedCode is the HTTP code returned for type RetrieveForNotificationsUnauthorized
const RetrieveForNotificationsUnauthorizedCode int = 401

/*RetrieveForNotificationsUnauthorized Unauthorized

swagger:response retrieveForNotificationsUnauthorized
*/
type RetrieveForNotificationsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewRetrieveForNotificationsUnauthorized creates RetrieveForNotificationsUnauthorized with default headers values
func NewRetrieveForNotificationsUnauthorized() *RetrieveForNotificationsUnauthorized {

	return &RetrieveForNotificationsUnauthorized{}
}

// WithPayload adds the payload to the retrieve for notifications unauthorized response
func (o *RetrieveForNotificationsUnauthorized) WithPayload(payload *apimodels.ErrorResponse) *RetrieveForNotificationsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve for notifications unauthorized response
func (o *RetrieveForNotificationsUnauthorized) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveForNotificationsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveForNotificationsInternalServerErrorCode is the HTTP code returned for type RetrieveForNotificationsInternalServerError
const RetrieveForNotificationsInternalServerErrorCode int = 500

/*RetrieveForNotificationsInternalServerError Internal error

swagger:response retrieveForNotificationsInternalServerError
*/
type RetrieveForNotificationsInternalServerError struct {
}

// NewRetrieveForNotificationsInternalServerError creates RetrieveForNotificationsInternalServerError with default headers values
func NewRetrieveForNotificationsInternalServerError() *RetrieveForNotificationsInternalServerError {

	return &RetrieveForNotificationsInternalServerError{}
}

// WriteResponse to the client
func (o *RetrieveForNotificationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
