// Code generated by go-swagger; DO NOT EDIT.

package teacher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveForNotificationsHandlerFunc turns a function with the right signature into a retrieve for notifications handler
type RetrieveForNotificationsHandlerFunc func(RetrieveForNotificationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveForNotificationsHandlerFunc) Handle(params RetrieveForNotificationsParams) middleware.Responder {
	return fn(params)
}

// RetrieveForNotificationsHandler interface for that can handle valid retrieve for notifications params
type RetrieveForNotificationsHandler interface {
	Handle(RetrieveForNotificationsParams) middleware.Responder
}

// NewRetrieveForNotifications creates a new http.Handler for the retrieve for notifications operation
func NewRetrieveForNotifications(ctx *middleware.Context, handler RetrieveForNotificationsHandler) *RetrieveForNotifications {
	return &RetrieveForNotifications{Context: ctx, Handler: handler}
}

/*RetrieveForNotifications swagger:route POST /retrievefornotifications teacher retrieveForNotifications

Retrieve For Notifications

retrieve_for_notifications

*/
type RetrieveForNotifications struct {
	Context *middleware.Context
	Handler RetrieveForNotificationsHandler
}

func (o *RetrieveForNotifications) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveForNotificationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
