// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/iAmPlus/microservice/models/apimodels"
)

// CreateRegisterNoContentCode is the HTTP code returned for type CreateRegisterNoContent
const CreateRegisterNoContentCode int = 204

/*CreateRegisterNoContent No content

swagger:response createRegisterNoContent
*/
type CreateRegisterNoContent struct {
}

// NewCreateRegisterNoContent creates CreateRegisterNoContent with default headers values
func NewCreateRegisterNoContent() *CreateRegisterNoContent {

	return &CreateRegisterNoContent{}
}

// WriteResponse to the client
func (o *CreateRegisterNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// CreateRegisterBadRequestCode is the HTTP code returned for type CreateRegisterBadRequest
const CreateRegisterBadRequestCode int = 400

/*CreateRegisterBadRequest Bad request <br>


swagger:response createRegisterBadRequest
*/
type CreateRegisterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewCreateRegisterBadRequest creates CreateRegisterBadRequest with default headers values
func NewCreateRegisterBadRequest() *CreateRegisterBadRequest {

	return &CreateRegisterBadRequest{}
}

// WithPayload adds the payload to the create register bad request response
func (o *CreateRegisterBadRequest) WithPayload(payload *apimodels.ErrorResponse) *CreateRegisterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create register bad request response
func (o *CreateRegisterBadRequest) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRegisterUnauthorizedCode is the HTTP code returned for type CreateRegisterUnauthorized
const CreateRegisterUnauthorizedCode int = 401

/*CreateRegisterUnauthorized Unauthorized

swagger:response createRegisterUnauthorized
*/
type CreateRegisterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewCreateRegisterUnauthorized creates CreateRegisterUnauthorized with default headers values
func NewCreateRegisterUnauthorized() *CreateRegisterUnauthorized {

	return &CreateRegisterUnauthorized{}
}

// WithPayload adds the payload to the create register unauthorized response
func (o *CreateRegisterUnauthorized) WithPayload(payload *apimodels.ErrorResponse) *CreateRegisterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create register unauthorized response
func (o *CreateRegisterUnauthorized) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRegisterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRegisterInternalServerErrorCode is the HTTP code returned for type CreateRegisterInternalServerError
const CreateRegisterInternalServerErrorCode int = 500

/*CreateRegisterInternalServerError Internal error

swagger:response createRegisterInternalServerError
*/
type CreateRegisterInternalServerError struct {
}

// NewCreateRegisterInternalServerError creates CreateRegisterInternalServerError with default headers values
func NewCreateRegisterInternalServerError() *CreateRegisterInternalServerError {

	return &CreateRegisterInternalServerError{}
}

// WriteResponse to the client
func (o *CreateRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
