// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/iAmPlus/microservice/models/apimodels"
)

// GetCommonStudentsOKCode is the HTTP code returned for type GetCommonStudentsOK
const GetCommonStudentsOKCode int = 200

/*GetCommonStudentsOK Get Common Students

swagger:response getCommonStudentsOK
*/
type GetCommonStudentsOK struct {

	/*
	  In: Body
	*/
	Payload *apimodels.CommonStudents `json:"body,omitempty"`
}

// NewGetCommonStudentsOK creates GetCommonStudentsOK with default headers values
func NewGetCommonStudentsOK() *GetCommonStudentsOK {

	return &GetCommonStudentsOK{}
}

// WithPayload adds the payload to the get common students o k response
func (o *GetCommonStudentsOK) WithPayload(payload *apimodels.CommonStudents) *GetCommonStudentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get common students o k response
func (o *GetCommonStudentsOK) SetPayload(payload *apimodels.CommonStudents) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommonStudentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCommonStudentsBadRequestCode is the HTTP code returned for type GetCommonStudentsBadRequest
const GetCommonStudentsBadRequestCode int = 400

/*GetCommonStudentsBadRequest Bad request <br>


swagger:response getCommonStudentsBadRequest
*/
type GetCommonStudentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewGetCommonStudentsBadRequest creates GetCommonStudentsBadRequest with default headers values
func NewGetCommonStudentsBadRequest() *GetCommonStudentsBadRequest {

	return &GetCommonStudentsBadRequest{}
}

// WithPayload adds the payload to the get common students bad request response
func (o *GetCommonStudentsBadRequest) WithPayload(payload *apimodels.ErrorResponse) *GetCommonStudentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get common students bad request response
func (o *GetCommonStudentsBadRequest) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommonStudentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCommonStudentsUnauthorizedCode is the HTTP code returned for type GetCommonStudentsUnauthorized
const GetCommonStudentsUnauthorizedCode int = 401

/*GetCommonStudentsUnauthorized Unauthorized

swagger:response getCommonStudentsUnauthorized
*/
type GetCommonStudentsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewGetCommonStudentsUnauthorized creates GetCommonStudentsUnauthorized with default headers values
func NewGetCommonStudentsUnauthorized() *GetCommonStudentsUnauthorized {

	return &GetCommonStudentsUnauthorized{}
}

// WithPayload adds the payload to the get common students unauthorized response
func (o *GetCommonStudentsUnauthorized) WithPayload(payload *apimodels.ErrorResponse) *GetCommonStudentsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get common students unauthorized response
func (o *GetCommonStudentsUnauthorized) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommonStudentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCommonStudentsInternalServerErrorCode is the HTTP code returned for type GetCommonStudentsInternalServerError
const GetCommonStudentsInternalServerErrorCode int = 500

/*GetCommonStudentsInternalServerError Internal error

swagger:response getCommonStudentsInternalServerError
*/
type GetCommonStudentsInternalServerError struct {
}

// NewGetCommonStudentsInternalServerError creates GetCommonStudentsInternalServerError with default headers values
func NewGetCommonStudentsInternalServerError() *GetCommonStudentsInternalServerError {

	return &GetCommonStudentsInternalServerError{}
}

// WriteResponse to the client
func (o *GetCommonStudentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
