// Code generated by go-swagger; DO NOT EDIT.

package apimodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PageState page state
//
// swagger:model PageState
type PageState struct {

	// page ID
	PageID int64 `json:"pageid,omitempty"`

	// page size
	PageSize int64 `json:"pagesize,omitempty"`
}

// Validate validates this page state
func (m *PageState) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PageState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageState) UnmarshalBinary(b []byte) error {
	var res PageState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
