// Code generated by go-swagger; DO NOT EDIT.

package apimodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetrieveForNotifications Retrieve for Notifications
//
// swagger:model retrieve_for_notifications
type RetrieveForNotifications struct {

	// notification
	Notification string `json:"notification,omitempty"`

	// teacher id
	TeacherID string `json:"teacher_id,omitempty"`
}

// Validate validates this retrieve for notifications
func (m *RetrieveForNotifications) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetrieveForNotifications) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetrieveForNotifications) UnmarshalBinary(b []byte) error {
	var res RetrieveForNotifications
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
